// get the user from acccess token
// 1. Checking if the token is valid or not
// 2. Wether the token was generated by our API or not
// 3. once validated, it will get user email from that token

import { getSession } from "../model/sessionModel.js";
import { findUserByEmail } from "../model/userModel.js";
import {
  generateAccessJWT,
  verifyAccessJWT,
  verifyRefreshJWT,
} from "../utility/jwtHelper.js";
import {
  buildErrorResponse,
  buildSuccessResponse,
} from "../utility/responseHelper.js";

// 4. Get user from our db using that email
const getUserFromAccessJWT = async (accessJWT) => {
  // check if the token exist in sesion storage
  const token = await getSession(accessJWT);

  if (!token?._id) {
    return false;
  }

  // validate accessJWT
  const decodedToken = verifyAccessJWT(accessJWT);

  if (!decodedToken?.email) {
    return false;
  }

  // token is valid
  // get user based on the decoded email
  const user = await findUserByEmail(decodedToken.email);

  return user;
};

export const userAuth = async (req, res, next) => {
  try {
    const { authorization } = req.headers;

    // find user based on auth token
    const user = await getUserFromAccessJWT(authorization);

    if (user?._id) {
      user.password = undefined;
      req.userInfo = user;
      next();
      return;
    }

    buildErrorResponse(res, "Invalid token, unauthorized");
  } catch (error) {
    buildErrorResponse(res, "Invalid token, unauthorized");
  }
};

export const refreshAuth = async (req, res, next) => {
  try {
    const { authorization } = req.headers;
    // validate and decode referesh token
    const decodedToken = verifyRefreshJWT(authorization);
    if (decodedToken?.email) {
      const user = await findUserByEmail(decodedToken.email);

      if (user?._id) {
        const accessJWT = generateAccessJWT(user.email);

        buildSuccessResponse(res, accessJWT, "New accessJWT");
        return;
      }
    }
  } catch (error) {
    buildErrorResponse(res, "Invalid token, unauthorized");
  }
};
